version : 2.1
orbs:
    build:
        docker:
            - image: circleci/node:latest
        steps:
        - checkout
        - run: npm install
        - snyk/scan:
            fail-on-issues: true
            monitor-on-build: true
            severity-threshold: high
            token-variable: SNYK_TOKEN
        
workflows:
    version: 2
    build_and_test:
        jobs:
        - build